name: ActionCallAPI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Set Up .NetCore
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.408'
        
    - name: Dotnet Restore
      run: |
        cd WebApi2_Estudantes/WebApi2_Estudantes/
        dotnet restore
        
    - name: dotnet RUN
      run: |
        cd WebApi2_Estudantes/WebApi2_Estudantes/
        dotnet run
